### PR TITLE
feat: apply clang-tidy fixes, use explicit struct for scanner info

### PR DESCRIPTION
**Pull request by amaanq**
Reasons for the scanner are pretty much the same here

https://github.com/MunifTanjim/tree-sitter-lua/pull/35

I renamed _EOF to EOF_ because all caps idents prefixed with underscores are reserved

Thanks!

### CODE REVIEW

**Comment by acristoffers** [comment]
Very nice, thank you. There is a `.clang-format` config in the repo, if you happen to have clang-format installed. I'll accept the pull and format the code myself, no problems. Thank you very much for the contribution!

**Comment by acristoffers** [comment]
Thank you very much for the contribution!

**Comment by amaanq** [comment]
P.S to benefit from the clang-tidy lints you can add a .clang-tidy file in the repo root and clangd will pick it up

A config I use that removes useless lints:
```yaml
Checks: "*,clang-analyzer-optin-performance.Padding,-modernize-use-trailing-return-type,-altera-*,-google-readability-todo,-cppcoreguidelines-avoid-magic-numbers,-llvmlibc-*,-readability-magic-numbers,-hicpp-signed-bitwise,-readability-function-cognitive-complexity"
HeaderFilterRegex: ""
```

**Comment by acristoffers** [comment]
Thanks, I added it. Do you run `clang-tidy` by hand? Do you use a plugin? I couldn't find it in mason.

**Comment by amaanq** [comment]
> Thanks, I added it. Do you run `clang-tidy` by hand? Do you use a plugin? I couldn't find it in mason.

I pass it as an arg to clang in my lsp setup 

https://github.com/amaanq/nvim-config/blob/64fd1a4a06bfae6a4253dbe3daea73222720a793/lua/plugins/extras/lang/clangd.lua#L47

**Pull request merged**
